import 'dart:convert';
import 'dart:async';
import 'package:flutter/material.dart';
import 'package:cuaca/models/cuaca_model.dart';
import 'package:cuaca/provider/cuaca_providers.dart';


class HomePageState extends State<HomePage> {
  Future<List<Autogenerated>> datas = getData();

  @override
  Widget build(BuildContext context) => Scaffold(
      appBar: AppBar(
        title: const Text("UAS : Ade Sulaeman Akbar"),
        centerTitle: true,
      ),
      body: Center(
        child: FutureBuilder<List<Autogenerated>>(
          future: datas,
          builder: (context, snapshot){
            if(snapshot.hasData){
              final data = snapshot.data!;
              return buildData(data);
            }else{
              return const Text("error Data");
            }
          },
        ),
      ),
  );

  Widget buildData(List<Autogenerated> dataJs) => ListView.builder(
    itemCount: dataJs.length,
    itemBuilder: (context, index) {
      final dataj = dataJs[index];

      String bodyData = 'Kondisi Awan : '+dataj.weather.Clouds+' \nKeterangan : ' + dataj.weather.description + ' \nIcon : ' + dataj.weather.icon;

      return Card(
        child: ListTile(
          title: Text("Cuaca Pamulang"),
          subtitle: Text(bodyData),
        ),
      );
    },
  );
}
